// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/crypto:gen_crypto_buildconfig"

#ifndef CRYPTO_CRYPTOBUILDCONFIG_H_
#define CRYPTO_CRYPTOBUILDCONFIG_H_

#define CHIP_CRYPTO_MBEDTLS 1
#define CHIP_CRYPTO_PSA 0
#define CHIP_CRYPTO_OPENSSL 0
#define CHIP_CRYPTO_BORINGSSL 0
#define CHIP_CRYPTO_PLATFORM 0
#define CHIP_CRYPTO_HSM 0
#define CHIP_CRYPTO_HSM_NXP 0

#endif  // CRYPTO_CRYPTOBUILDCONFIG_H_
