/*
 * Copyright (c) 2023  Moddable Tech, Inc.
 *
 *   This file is part of the Moddable SDK.
 * 
 *   This work is licensed under the
 *       Creative Commons Attribution 4.0 International License.
 *   To view a copy of this license, visit
 *       <http://creativecommons.org/licenses/by/4.0>.
 *   or send a letter to Creative Commons, PO Box 1866,
 *   Mountain View, CA 94042, USA.
 *
 */

export default Object.freeze([
	{
		id: "beatblender",
		title: "Beat Blender",
		description: "A late night blend of deep-house and downtempo chill.",
		genre: "electronic",
		image: { texture:{ path:"beatblender.png" }, width:80, height:80 },
		color: { fill:["#240d22", "#000000"] },
	},
	{
		id: "brfm",
		title: "Black Rock FM",
		description: "From the Playa to the world, for the annual Burning Man festival.",
		genre: "eclectic",
		image: { texture:{ path:"brfm.png" }, width:80, height:80 },
		color: { fill:["#8e6b54", "#000000"] },
	},
	{
		id: "bootliquor",
		title: "Boot Liquor",
		description: "Americana Roots music for Cowhands, Cowpokes and Cowtippers",
		genre: "americana",
		image: { texture:{ path:"bootliquor.png" }, width:80, height:80 },
		color: { fill:["#c06e3e", "#000000"] },
	},
	{
		id: "cliqhop",
		title: "cliqhop idm",
		description: "Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.",
		genre: "electronic",
		image: { texture:{ path:"cliqhop.png" }, width:80, height:80 },
		color: { fill:["#9fa36f", "#000000"] },
	},
	{
		id: "covers",
		title: "Covers",
		description: "Just covers. Songs you know by artists you don't. We've got you covered. ",
		genre: "eclectic",
		image: { texture:{ path:"covers.png" }, width:80, height:80 },
		color: { fill:["#74655d", "#000000"] },
	},
	{
		id: "deepspaceone",
		title: "Deep Space One",
		description: "Deep ambient electronic, experimental and space music. For inner and outer space exploration.",
		genre: "ambient",
		image: { texture:{ path:"deepspaceone.png" }, width:80, height:80 },
		color: { fill:["#384d6d", "#000000"] },
	},
	{
		id: "defcon",
		title: "DEF CON Radio",
		description: "Music for Hacking. The DEF CON Year-Round Channel.",
		genre: "electronic specials",
		image: { texture:{ path:"defcon.png" }, width:80, height:80 },
		color: { fill:["#3c3738", "#000000"] },
	},
	{
		id: "digitalis",
		title: "Digitalis",
		description: "Digitally affected analog rock to calm the agitated heart.",
		genre: "electronic alternative",
		image: { texture:{ path:"digitalis.png" }, width:80, height:80 },
		color: { fill:["#5f4667", "#000000"] },
	},
	{
		id: "dronezone",
		title: "Drone Zone",
		description: "Served best chilled, safe with most medications. Atmospheric textures with minimal beats.",
		genre: "ambient",
		image: { texture:{ path:"dronezone.png" }, width:80, height:80 },
		color: { fill:["#81a3ca", "#000000"] },
	},
	{
		id: "dubstep",
		title: "Dub Step Beyond",
		description: "Dubstep, Dub and Deep Bass. May damage speakers at high volume.",
		genre: "electronic",
		image: { texture:{ path:"dubstep.png" }, width:80, height:80 },
		color: { fill:["#291d7b", "#000000"] },
	},
	{
		id: "fluid",
		title: "Fluid",
		description: "Drown in the electronic sound of instrumental hiphop, future soul and liquid trap.",
		genre: "electronic hiphop",
		image: { texture:{ path:"fluid.png" }, width:80, height:80 },
		color: { fill:["#97abb4", "#000000"] },
	},
	{
		id: "folkfwd",
		title: "Folk Forward",
		description: "Indie Folk, Alt-folk and the occasional folk classics. ",
		genre: "folk alternative",
		image: { texture:{ path:"folkfwd.png" }, width:80, height:80 },
		color: { fill:["#9eaea6", "#000000"] },
	},
	{
		id: "groovesalad",
		title: "Groove Salad",
		description: "A nicely chilled plate of ambient/downtempo beats and grooves.",
		genre: "ambient electronic",
		image: { texture:{ path:"groovesalad.png" }, width:80, height:80 },
		color: { fill:["#22611b", "#000000"] },
	},
	{
		id: "gsclassic",
		title: "Groove Salad Classic",
		description: "The classic (early 2000s) version of a nicely chilled plate of ambient/downtempo beats and grooves.",
		genre: "ambient electronic",
		image: { texture:{ path:"gsclassic.png" }, width:80, height:80 },
		color: { fill:["#5c7e55", "#000000"] },
	},
	{
		id: "reggae",
		title: "Heavyweight Reggae",
		description: "Reggae, Ska, Rocksteady classic and deep tracks.",
		genre: "reggae",
		image: { texture:{ path:"reggae.png" }, width:80, height:80 },
		color: { fill:["#565953", "#000000"] },
	},
	{
		id: "illstreet",
		title: "Illinois Street Lounge",
		description: "Classic bachelor pad, playful exotica and vintage music of tomorrow.",
		genre: "lounge",
		image: { texture:{ path:"illstreet.png" }, width:80, height:80 },
		color: { fill:["#5f9099", "#000000"] },
	},
	{
		id: "indiepop",
		title: "Indie Pop Rocks!",
		description: "New and classic favorite indie pop tracks.",
		genre: "alternative rock",
		image: { texture:{ path:"indiepop.png" }, width:80, height:80 },
		color: { fill:["#7a675c", "#000000"] },
	},
	{
		id: "seventies",
		title: "Left Coast 70s",
		description: "Mellow album rock from the Seventies. Yacht not required.",
		genre: "70s rock",
		image: { texture:{ path:"seventies.png" }, width:80, height:80 },
		color: { fill:["#87889c", "#000000"] },
	},
	{
		id: "lush",
		title: "Lush",
		description: "Sensuous and mellow female vocals, many with an electronic influence.",
		genre: "electronic",
		image: { texture:{ path:"lush.png" }, width:80, height:80 },
		color: { fill:["#8c7769", "#000000"] },
	},
	{
		id: "metal",
		title: "Metal Detector",
		description: "From black to doom, prog to sludge, thrash to post, stoner to crossover, punk to industrial.",
		genre: "metal",
		image: { texture:{ path:"metal.png" }, width:80, height:80 },
		color: { fill:["#792b2e", "#000000"] },
	},
	{
		id: "missioncontrol",
		title: "Mission Control",
		description: "Celebrating NASA and Space Explorers everywhere.",
		genre: "ambient electronic",
		image: { texture:{ path:"missioncontrol.png" }, width:80, height:80 },
		color: { fill:["#4b484d", "#000000"] },
	},
	{
		id: "n5md",
		title: "n5MD Radio",
		description: "Emotional Experiments in Music: Ambient, modern composition, post-rock, & experimental electronic music",
		genre: "specials",
		image: { texture:{ path:"n5md.png" }, width:80, height:80 },
		color: { fill:["#404040", "#000000"] },
	},
	{
		id: "poptron",
		title: "PopTron",
		description: "Electropop and indie dance rock with sparkle and pop.",
		genre: "alternative",
		image: { texture:{ path:"poptron.png" }, width:80, height:80 },
		color: { fill:["#578e93", "#000000"] },
	},
	{
		id: "secretagent",
		title: "Secret Agent",
		description: "The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!",
		genre: "lounge",
		image: { texture:{ path:"secretagent.png" }, width:80, height:80 },
		color: { fill:["#6f271c", "#000000"] },
	},
	{
		id: "7soul",
		title: "Seven Inch Soul",
		description: "Vintage soul tracks from the original 45 RPM vinyl.",
		genre: "oldies",
		image: { texture:{ path:"7soul.png" }, width:80, height:80 },
		color: { fill:["#5f4e2d", "#000000"] },
	},
	{
		id: "sf1033",
		title: "SF 10-33",
		description: "Ambient music mixed with the sounds of San Francisco public safety radio traffic.",
		genre: "ambient news",
		image: { texture:{ path:"sf1033.png" }, width:80, height:80 },
		color: { fill:["#2e8248", "#000000"] },
	},
	{
		id: "sfinsf",
		title: "SF in SF",
		description: "Author readings and discussions from the science fiction, fantasy, horror, and genre literary fields.",
		genre: "spoken",
		image: { texture:{ path:"sfinsf.png" }, width:80, height:80 },
		color: { fill:["#b09ca8", "#000000"] },
	},
	{
		id: "scanner",
		title: "SF Police Scanner",
		description: "San Francisco Public Safety Scanner Feed",
		genre: "live news",
		image: { texture:{ path:"scanner.png" }, width:80, height:80 },
		color: { fill:["#2e8248", "#000000"] },
	},
	{
		id: "live",
		title: "SomaFM Live",
		description: "Special Live Events and rebroadcasts of past live events",
		genre: "specials",
		image: { texture:{ path:"live.png" }, width:80, height:80 },
		color: { fill:["#3d2b23", "#000000"] },
	},
	{
		id: "specials",
		title: "SomaFM Specials",
		description: "Now featuring Tiki Time, Bossa Beyond, Surf Report & More!",
		genre: "specials",
		image: { texture:{ path:"specials.png" }, width:80, height:80 },
		color: { fill:["#3d2b23", "#000000"] },
	},
	{
		id: "sonicuniverse",
		title: "Sonic Universe",
		description: "Transcending the world of jazz with eclectic, avant-garde takes on tradition.",
		genre: "jazz",
		image: { texture:{ path:"sonicuniverse.png" }, width:80, height:80 },
		color: { fill:["#56453b", "#000000"] },
	},
	{
		id: "spacestation",
		title: "Space Station Soma",
		description: "Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.",
		genre: "electronic",
		image: { texture:{ path:"spacestation.png" }, width:80, height:80 },
		color: { fill:["#81756f", "#000000"] },
	},
	{
		id: "suburbsofgoa",
		title: "Suburbs of Goa",
		description: "Desi-influenced Asian world beats and beyond.",
		genre: "world",
		image: { texture:{ path:"suburbsofgoa.png" }, width:80, height:80 },
		color: { fill:["#7a675a", "#000000"] },
	},
	{
		id: "synphaera",
		title: "Synphaera Radio",
		description: "Featuring the music from an independent record label focused on modern electronic ambient and space music.",
		genre: "ambient electronic",
		image: { texture:{ path:"synphaera.png" }, width:80, height:80 },
		color: { fill:["#676074", "#000000"] },
	},
	{
		id: "darkzone",
		title: "The Dark Zone",
		description: "The darker side of deep ambient. Music for staring into the Abyss. ",
		genre: "ambient",
		image: { texture:{ path:"darkzone.png" }, width:80, height:80 },
		color: { fill:["#4e4734", "#000000"] },
	},
	{
		id: "thetrip",
		title: "The Trip",
		description: "Progressive house / trance. Tip top tunes.",
		genre: "electronic",
		image: { texture:{ path:"thetrip.png" }, width:80, height:80 },
		color: { fill:["#3e3f37", "#000000"] },
	},
	{
		id: "thistle",
		title: "ThistleRadio",
		description: "Exploring music from Celtic roots and branches",
		genre: "celtic world",
		image: { texture:{ path:"thistle.png" }, width:80, height:80 },
		color: { fill:["#69724f", "#000000"] },
	},
	{
		id: "u80s",
		title: "Underground 80s",
		description: "Early 80s UK Synthpop and a bit of New Wave.",
		genre: "alternative electronic",
		image: { texture:{ path:"u80s.png" }, width:80, height:80 },
		color: { fill:["#a888a2", "#000000"] },
	},
	{
		id: "vaporwaves",
		title: "Vaporwaves",
		description: "All Vaporwave. All the time.",
		genre: "electronic",
		image: { texture:{ path:"vaporwaves.png" }, width:80, height:80 },
		color: { fill:["#a04ec8", "#000000"] },
	},
], true);
