// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/lwip:gen_lwip_buildconfig"

#ifndef LWIP_LWIP_BUILDCONFIG_H_
#define LWIP_LWIP_BUILDCONFIG_H_

#define HAVE_LWIP_UDP_BIND_NETIF 1

#endif  // LWIP_LWIP_BUILDCONFIG_H_
