// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/app:gen_app_buildconfig"

#ifndef APP_APPBUILDCONFIG_H_
#define APP_APPBUILDCONFIG_H_

#define CHIP_CONFIG_IM_PRETTY_PRINT 0
#define CHIP_CONFIG_IM_FORCE_FABRIC_QUOTA_CHECK 0
#define CHIP_CONFIG_ENABLE_SESSION_RESUMPTION 1
#define CHIP_CONFIG_ACCESS_CONTROL_POLICY_LOGGING_VERBOSITY 0

#endif  // APP_APPBUILDCONFIG_H_
