/*
 * Copyright (c) 2024-2025 Moddable Tech, Inc.
 *
 *   This file is part of the Moddable SDK Runtime.
 * 
 *   The Moddable SDK Runtime is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 * 
 *   The Moddable SDK Runtime is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 * 
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with the Moddable SDK Runtime.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

import config from "mc/config"

const BLACK = "black";
const DARK = "#404040";
const GRAY = "#808080";
const LITE = "#C0C0C0";
const WHITE = "white";
const TRANSPARENT = "transparent";

const assets = {
	colors: {
		BLACK,
		DARK,
		GRAY,
		LITE,
		WHITE,
		TRANSPARENT,
	},
	skins: {
		screen: { fill:"#011430" },
		
		logo: { texture:{ path: "mod-logo.png" }, width:144, height:56, color:WHITE },
		microphone: { texture:{ path: "microphone.png" }, width:100, height:100, variants:100, color:[WHITE,GRAY] },
		microphoneSmall: { texture:{ path: "microphone-small.png" }, width:24, height:24, variants:24, color:[BLACK,GRAY] },
		scrollbarY: { texture:{ path: "scrollbarY.png" }, width:20, height:60, top:10, bottom:10, color:GRAY },
		star2: { texture:{ path: "star-4x4.png" }, width:4, height:4, variants:4 },
		star3: { texture:{ path: "star-5x5.png" }, width:5, height:5, variants:5 },
		star6: { texture:{ path: "star-8x8.png" }, width:8, height:8, variants:8 },
		star9: { texture:{ path: "star-11x11.png" }, width:11, height:11, variants:11 },
		star2_2: { texture:{ path: "star2-4x4.png" }, width:4, height:4, variants:4 },
		star2_3: { texture:{ path: "star2-5x5.png" }, width:5, height:5, variants:5 },
		star2_6: { texture:{ path: "star2-8x8.png" }, width:8, height:8, variants:8 },
		star2_9: { texture:{ path: "star2-11x11.png" }, width:11, height:11, variants:11 },

		providerRow: { fill:["#E0E0E0"], stroke:LITE, bottom:1 },
		personaRow: { fill:[WHITE,LITE], stroke:LITE, bottom:1 },
		homeTitle: { stroke:GRAY, bottom:1, }, 
		
		back: { texture:{ path: "back-arrow-mask.png" }, width:12, height:20, color:[WHITE,LITE] },
		check: { texture:{ path: "check-mask.png" }, width:24, height:20, color:DARK },
		forward: { texture:{ path: "forward-arrow-mask.png" }, width:12, height:20, color:GRAY },
		gear: { texture:{ path: "gear-mask.png" }, width:23, height:23, color:[GRAY,BLACK] },
		
		error: { fill:WHITE },
		voiceLabel: { fill:["#ffe8dc", "#dcffe8", "#e8dcff", "#e8e8e8"] },
	},
	styles: {
		screen: { font:"18px Roboto", color:WHITE },
		
		personaTitle: { font:"medium 16px Roboto", color:BLACK, horizontal:"left" },
		personaSubtitle: { font:"light 14px Roboto", color:[BLACK, "red"], horizontal:"left" },
		
		homeTitle: { font:"medium 16px Roboto", color:WHITE, horizontal:"left" },
		homePrompt: { font:"medium 14px Roboto", color:WHITE, horizontal:"left" },
	
		error: { font:"light 14px Roboto", color:BLACK, horizontal:"left" },
		voiceLabel: { font:"light 14px Roboto", color:BLACK, left:4, right:4, top:2, bottom:2 },
	},
	textures: {
		bubble: { path: "bubble.png" },
		button: { path: "button.png" },
		glow: { path: "glow.png" },
		level: { path: "level.png" },
		wait: { path: "wait.png" },
	},
	
	services: {
		deepgram: {
			color: "#0cc35c",
			icon:  { texture:{ path: "deepgram-logo.png" }, width:64, height:64 },
			iconSmall: { texture:{ path: "deepgram-logo-small.png" }, width:24, height:24 },
			key: config.deepgramKey,
			title: "Deepgram Agent",
			specifier: "deepgramAgent",
			transcript: true,
			voices: [
				{ name:"Amalthea", id:"aura-2-amalthea-en", gender:"Female", age:"Young Adult", accent:"Filipino", usage:"Casual chat", description:["Engaging", "Natural", "Cheerful"] },
				{ name:"Andromeda", id:"aura-2-andromeda-en", gender:"Female", age:"Adult", accent:"American", usage:["Customer service", "IVR"], description:["Casual", "Expressive", "Comfortable"] },
				{ name:"Apollo", id:"aura-2-apollo-en", gender:"Male", age:"Adult", accent:"American", usage:"Casual chat", description:["Confident", "Comfortable", "Casual"] },
				{ name:"Arcas", id:"aura-2-arcas-en", gender:"Male", age:"Adult", accent:"American", usage:["Customer service", "Casual chat"], description:["Natural", "Smooth", "Clear", "Comfortable"] },
				{ name:"Aries", id:"aura-2-aries-en", gender:"Male", age:"Adult", accent:"American", usage:"Casual chat", description:["Warm", "Energetic", "Caring"] },
				{ name:"Asteria", id:"aura-2-asteria-en", gender:"Female", age:"Adult", accent:"American", usage:"Advertising", description:["Clear", "Confident", "Knowledgeable", "Energetic"] },
				{ name:"Athena", id:"aura-2-athena-en", gender:"Female", age:"Mature", accent:"American", usage:"Storytelling", description:["Calm", "Smooth", "Professional"] },
				{ name:"Atlas", id:"aura-2-atlas-en", gender:"Male", age:"Mature", accent:"American", usage:"Advertising", description:["Enthusiastic", "Confident", "Approachable", "Friendly"] },
				{ name:"Aurora", id:"aura-2-aurora-en", gender:"Female", age:"Adult", accent:"American", usage:"Interview", description:["Cheerful", "Expressive", "Energetic"] },
				{ name:"Callista", id:"aura-2-callista-en", gender:"Female", age:"Adult", accent:"American", usage:"IVR", description:["Clear", "Energetic", "Professional", "Smooth"] },
				{ name:"Cora", id:"aura-2-cora-en", gender:"Female", age:"Adult", accent:"American", usage:"Storytelling", description:["Smooth", "Melodic", "Caring"] },
				{ name:"Cordelia", id:"aura-2-cordelia-en", gender:"Female", age:"Young Adult", accent:"American", usage:"Storytelling", description:["Approachable", "Warm", "Polite"] },
				{ name:"Delia", id:"aura-2-delia-en", gender:"Female", age:"Young Adult", accent:"American", usage:"Interview", description:["Casual", "Friendly", "Cheerful", "Breathy"] },
				{ name:"Draco", id:"aura-2-draco-en", gender:"Male", age:"Adult", accent:"British", usage:"Storytelling", description:["Warm", "Approachable", "Trustworthy", "Baritone"] },
				{ name:"Electra", id:"aura-2-electra-en", gender:"Female", age:"Adult", accent:"American", usage:["IVR", "Advertising", "Customer service"], description:["Professional", "Engaging", "Knowledgeable"] },
				{ name:"Harmonia", id:"aura-2-harmonia-en", gender:"Female", age:"Adult", accent:"American", usage:"Customer service", description:["Empathetic", "Clear", "Calm", "Confident"] },
				{ name:"Helena", id:"aura-2-helena-en", gender:"Female", age:"Adult", accent:"American", usage:["IVR", "Casual chat"], description:["Caring", "Natural", "Positive", "Friendly"] },
				{ name:"Hera", id:"aura-2-hera-en", gender:"Female", age:"Adult", accent:"American", usage:"Informative", description:["Smooth", "Warm", "Professional"] },
				{ name:"Hermes", id:"aura-2-hermes-en", gender:"Male", age:"Adult", accent:"American", usage:"Informative", description:["Expressive", "Engaging", "Professional"] },
				{ name:"Hyperion", id:"aura-2-hyperion-en", gender:"Male", age:"Adult", accent:"Australian", usage:"Interview", description:["Caring", "Warm", "Empathetic"] },
				{ name:"Iris", id:"aura-2-iris-en", gender:"Female", age:"Young Adult", accent:"American", usage:["IVR", "Advertising", "Customer service"], description:["Cheerful", "Positive", "Approachable"] },
				{ name:"Janus", id:"aura-2-janus-en", gender:"Female", age:"Adult", accent:"American", usage:"Storytelling", description:["Southern", "Smooth", "Trustworthy"] },
				{ name:"Juno", id:"aura-2-juno-en", gender:"Female", age:"Adult", accent:"American", usage:"Interview", description:["Natural", "Engaging", "Melodic", "Breathy"] },
				{ name:"Jupiter", id:"aura-2-jupiter-en", gender:"Male", age:"Adult", accent:"American", usage:"Informative", description:["Expressive", "Knowledgeable", "Baritone"] },
				{ name:"Luna", id:"aura-2-luna-en", gender:"Female", age:"Young Adult", accent:"American", usage:"IVR", description:["Friendly", "Natural", "Engaging"] },
				{ name:"Mars", id:"aura-2-mars-en", gender:"Male", age:"Adult", accent:"American", usage:"Customer service", description:["Smooth", "Patient", "Trustworthy", "Baritone"] },
				{ name:"Minerva", id:"aura-2-minerva-en", gender:"Female", age:"Adult", accent:"American", usage:"Storytelling", description:["Positive", "Friendly", "Natural"] },
				{ name:"Neptune", id:"aura-2-neptune-en", gender:"Male", age:"Adult", accent:"American", usage:"Customer service", description:["Professional", "Patient", "Polite"] },
				{ name:"Odysseus", id:"aura-2-odysseus-en", gender:"Male", age:"Adult", accent:"American", usage:"Advertising", description:["Calm", "Smooth", "Comfortable", "Professional"] },
				{ name:"Ophelia", id:"aura-2-ophelia-en", gender:"Female", age:"Adult", accent:"American", usage:"Interview", description:["Expressive", "Enthusiastic", "Cheerful"] },
				{ name:"Orion", id:"aura-2-orion-en", gender:"Male", age:"Adult", accent:"American", usage:"Informative", description:["Approachable", "Comfortable", "Calm", "Polite"] },
				{ name:"Orpheus", id:"aura-2-orpheus-en", gender:"Male", age:"Adult", accent:"American", usage:["Customer service", "Storytelling"], description:["Professional", "Clear", "Confident", "Trustworthy"] },
				{ name:"Pandora", id:"aura-2-pandora-en", gender:"Female", age:"Adult", accent:"British", usage:["IVR", "Informative"], description:["Smooth", "Calm", "Melodic", "Breathy"] },
				{ name:"Phoebe", id:"aura-2-phoebe-en", gender:"Female", age:"Adult", accent:"American", usage:"Customer service", description:["Energetic", "Warm", "Casual"] },
				{ name:"Pluto", id:"aura-2-pluto-en", gender:"Male", age:"Adult", accent:"American", usage:["Interview", "Storytelling"], description:["Smooth", "Calm", "Empathetic", "Baritone"] },
				{ name:"Saturn", id:"aura-2-saturn-en", gender:"Male", age:"Adult", accent:"American", usage:"Customer service", description:["Knowledgeable", "Confident", "Baritone"] },
				{ name:"Selene", id:"aura-2-selene-en", gender:"Female", age:"Adult", accent:"American", usage:"Informative", description:["Expressive", "Engaging", "Energetic"] },
				{ name:"Thalia", id:"aura-2-thalia-en", gender:"Female", age:"Adult", accent:"American", usage:["Casual chat", "Customer service", "IVR"], description:["Clear", "Confident", "Energetic", "Enthusiastic"] },
				{ name:"Theia", id:"aura-2-theia-en", gender:"Female", age:"Adult", accent:"American", usage:"Informative", description:["Expressive", "Polite", "Sincere"] },
				{ name:"Vesta", id:"aura-2-vesta-en", gender:"Female", age:"Adult", accent:"American", usage:["Customer service", "Interview", "Storytelling"], description:["Natural", "Expressive", "Patient", "Empathetic"] },
				{ name:"Zeus", id:"aura-2-zeus-en", gender:"Male", age:"Adult", accent:"American", usage:"IVR", description:["Deep", "Trustworthy", "Smooth"] },
			],
			defaultVoiceID: "aura-2-thalia-en",
			providers: [
				{	name:"Anthropic", id:"anthropic",
					models: [
						{ name:"Claude Sonnet 4", id:"claude-sonnet-4-20250514" },			
						{ name:"Claude Haiku 3.5", id:"claude-3-5-haiku-latest" },
					],
				},
				{	name:"Google", id:"google",
					models: [
						{ name:"Gemini 2.5 Flash", id:"gemini-2.5-flash" },
						{ name:"Gemini 2.5 Flash Lite", id:"gemini-2.5-flash-lite" },
						{ name:"Gemini 2.0 Flash", id:"gemini-2.0-flash" },
						{ name:"Gemini 2.0 Flash Lite", id:"gemini-2.0-flash-lite" },
					],
				},
				{	name:"OpenAI", id:"open_ai",
					models: [
						{ name:"GPT 5", id:"gpt-5" },
						{ name:"GPT 5 Mini", id:"gpt-5-mini" },
						{ name:"GPT 5 Nano", id:"gpt-5-nano" },
						{ name:"GPT 4.1", id:"gpt-4.1" },
						{ name:"GPT 4.1 Mini", id:"gpt-4.1-mini" },
						{ name:"GPT 4.1 Nano", id:"gpt-4.1-nano" },
						{ name:"GPT 4o", id:"gpt-4o" },
						{ name:"GPT 4o Mini", id:"gpt-4o-mini" },
					],
				},
			],
			defaultProviderID: "anthropic",
			defaultModelID: "claude-sonnet-4-20250514",
		},
		elevenLabs: {
			color: "#959595",
			icon:  { texture:{ path: "elevenLabs-logo.png" }, width:64, height:64 },
			iconSmall: { texture:{ path: "elevenLabs-logo-small.png" }, width:24, height:24 },
			key: config.elevenLabsKey,
			title: "ElevenLabs Agent",
			specifier: "elevenLabsAgent",
			transcript: true,
			voices: [
				{ name:"Adam", id:"pNInz6obpgDQGcFmaJgB", accent:"American", age:"Middle Aged", description:"", gender:"Male", usage:"Social Media" },
				{ name:"Alice", id:"Xb7hH8MSUJpSbSDYk0k2", accent:"British", age:"Middle Aged", description:"Professional", gender:"Female", usage:"Advertisement" },
				{ name:"Bill", id:"pqHfZKP75CvOlQylNhV4", accent:"American", age:"Old", description:"Crisp", gender:"Male", usage:"Advertisement" },
				{ name:"Brian", id:"nPczCjzI2devNBz1zQrb", accent:"American", age:"Middle Aged", description:"Classy", gender:"Male", usage:"Social Media" },
				{ name:"Callum", id:"N2lVS1w4EtoT3dr4eOWO", accent:"American", age:"Middle Aged", description:"", gender:"Male", usage:"Characters Animation" },
				{ name:"Charlie", id:"IKne3meq5aSn9XLyUdCD", accent:"Australian", age:"Young", description:"Hyped", gender:"Male", usage:"Conversational" },
				{ name:"Chris", id:"iP95p4xoKVk53GoZ742B", accent:"American", age:"Middle Aged", description:"Casual", gender:"Male", usage:"Conversational" },
				{ name:"Daniel", id:"onwK4e9ZLuTAKqWW03F9", accent:"British", age:"Middle Aged", description:"Formal", gender:"Male", usage:"Informative Educational" },
				{ name:"Eric", id:"cjVigY5qzO86Huf0OWal", accent:"American", age:"Middle Aged", description:"Classy", gender:"Male", usage:"Conversational" },
				{ name:"George", id:"JBFqnCBsd6RMkjVDRZzb", accent:"British", age:"Middle Aged", description:"Mature", gender:"Male", usage:"Narrative Story" },
				{ name:"Harry", id:"SOYHLrjzK2X1ezoPC6cr", accent:"American", age:"Young", description:"Rough", gender:"Male", usage:"Characters Animation" },
				{ name:"Jessica", id:"cgSgspJ2msm6clMCkdW9", accent:"American", age:"Young", description:"Cute", gender:"Female", usage:"Conversational" },
				{ name:"Laura", id:"FGY2WhTYpPnrIDTdsKH5", accent:"American", age:"Young", description:"Sassy", gender:"Female", usage:"Social Media" },
				{ name:"Liam", id:"TX3LPaxmHKxFdv7VOQHJ", accent:"American", age:"Young", description:"Confident", gender:"Male", usage:"Social Media" },
				{ name:"Lily", id:"pFZP5JQG7iQjIQuC4Bku", accent:"British", age:"Middle Aged", description:"Confident", gender:"Female", usage:"Informative Educational" },
				{ name:"Matilda", id:"XrExE9yKIg1WjnnlVkGX", accent:"American", age:"Middle Aged", description:"Upbeat", gender:"Female", usage:"Informative Educational" },
				{ name:"River", id:"SAz9YHcvj6GT2YYXdXww", accent:"American", age:"Middle Aged", description:"Calm", gender:"Neutral", usage:"Conversational" },
				{ name:"Roger", id:"CwhRBWXzGAHq8TQ4Fs17", accent:"American", age:"Middle Aged", description:"Classy", gender:"Male", usage:"Conversational" },
				{ name:"Sarah", id:"EXAVITQu4vr4xnSDxMaL", accent:"American", age:"Young", description:"Professional", gender:"Female", usage:"Entertainment Tv" },
				{ name:"Will", id:"bIHbv24MWmeRgasZH58o", accent:"American", age:"Young", description:"Chill", gender:"Male", usage:"Conversational" },
			],
			defaultVoiceID: "pNInz6obpgDQGcFmaJgB",
			providers: [
				{	name:"Anthropic", id:"ANTHROPIC",
					models: [
						{ name:"Claude Sonnet 4.5", id:"claude-sonnet-4-5" },			
						{ name:"Claude Haiku 4.5", id:"claude-haiku-4-5" },
						{ name:"Claude Sonnet 4", id:"claude-sonnet-4" },			
						{ name:"Claude Sonnet 3.7", id:"claude-3-7-sonnet" },			
						{ name:"Claude Sonnet 3.5", id:"claude-3-5-sonnet" },			
						{ name:"Claude Haiku 3", id:"claude-3-haiku" },			
					],
				},
				{	name:"Google", id:"GOOGLE",
					models: [
						{ name:"Gemini 3 Pro Preview", id:"gemini-3-pro-preview" },
						{ name:"Gemini 2.5 Flash", id:"gemini-2.5-flash" },
						{ name:"Gemini 2.5 Flash Lite", id:"gemini-2.5-flash-lite" },
						{ name:"Gemini 2.0 Flash", id:"gemini-2.0-flash" },
						{ name:"Gemini 2.0 Flash Lite", id:"gemini-2.0-flash-lite" },
						{ name:"Gemini 1.5 Pro", id:"gemini-1.5-pro" },
						{ name:"Gemini 1.5 Flash", id:"gemini-1.5-flash" },
					],
				},
				{	name:"OpenAI", id:"OPEN_AI",
					models: [
						{ name:"GPT 5.1", id:"gpt-5.1" },
						{ name:"GPT 5", id:"gpt-5" },
						{ name:"GPT 5 Mini", id:"gpt-5-mini" },
						{ name:"GPT 5 Nano", id:"gpt-5-nano" },
						{ name:"GPT 4.1", id:"gpt-4.1" },
						{ name:"GPT 4.1 Mini", id:"gpt-4.1-mini" },
						{ name:"GPT 4.1 Nano", id:"gpt-4.1-nano" },
						{ name:"GPT 4o", id:"gpt-4o" },
						{ name:"GPT 4o Mini", id:"gpt-4o-mini" },
						{ name:"GPT 4", id:"gpt-4" },
						{ name:"GPT 4 Turbo", id:"gpt-4-turbo" },
						{ name:"GPT 3.5 Turbo", id:"gpt-3.5-turbo" },
					],
				},
			],
			defaultProviderID: "ANTHROPIC",
			defaultModelID: "claude-haiku-4-5",
		},
		gemini: {
			color: "#4e87d3",
			icon:  { texture:{ path: "gemini-logo.png" }, width:64, height:64 },
			iconSmall: { texture:{ path: "gemini-logo-small.png" }, width:24, height:24 },
			key: config.geminiAPIKey,
			title: "Google Gemini Live",
			specifier: "googleGeminiLive",
			transcript: true,
			voices: [
				{ name:"Aoede", id:"aoede", gender:"Female" },
				{ name:"Charon", id:"charon", gender:"Male" },
				{ name:"Fenrir", id:"fenrir", gender:"Male" },
				{ name:"Kore", id:"kore", gender:"Female" },
				{ name:"Leda", id:"leda", gender:"Female" },
				{ name:"Orus", id:"orus", gender:"Male" },
				{ name:"Puck", id:"puck", gender:"Male" },
				{ name:"Zephyr", id:"zephyr", gender:"Female" },
			],
			defaultVoiceID: "puck",
			defaultProviderID: "",
			defaultModelID: "",
		},
		hume: {
			color: "#9a8dea",
			icon:  { texture:{ path: "hume-logo.png" }, width:64, height:64 },
			iconSmall: { texture:{ path: "hume-logo-small.png" }, width:24, height:24 },
			key: config.humeAIKey,
			title: "Hume AI EVI",
			specifier: "humeAIEVI",
			transcript: true,
			voices: [	
				{ name: "Alice Bennett", id: "a7ecc00a-6fc0-4546-8126-e12cfd8de3bf", accent: "British", age: "Young", gender: "Female" },
				{ name: "American Lead Actress", id: "43e411b3-b2cc-40da-b742-4abf0e3557b2", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Articulate ASMR British Narrator", id: "4652d91b-edaf-42c5-abd4-904009422de3", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Aunt Tea", id: "1a655f88-551e-4633-a502-4c0d668168e8", accent: "Nigerian", age: "Old", gender: "Female" },
				{ name: "Ava Song", id: "5bb7de05-c8fe-426a-8fcc-ba4fc4ce9f9c", accent: "American", age: "Young", gender: "Female" },
				{ name: "Awe Inspired Guy", id: "2a7b176a-ca45-4ff8-8a65-56f873a5fdc7", accent: "American", age: "Young", gender: "Male" },
				{ name: "Big Dicky", id: "95f9baac-4512-4edb-a73e-2070784ccc2f", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Booming American Narrator", id: "445d65ed-a87f-4140-9820-daf6d4f0a200", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Booming British Narrator", id: "84aaf67b-dcab-409d-9f48-8c4aa7abbb24", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Brooding Intellectual Man", id: "15f594d3-0683-4585-b799-ce12e939a0e2", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "California Frat Bro", id: "a3d1e23c-403e-423b-aeae-c568ad0bccba", accent: "American", age: "Young", gender: "Male" },
				{ name: "Campfire Narrator", id: "b89de4b1-3df6-4e4f-a054-9aed4351092d", accent: "American", age: "Old", gender: "Male" },
				{ name: "Caring Mother", id: "97fe9008-8584-4d56-8453-bd8c7ead3663", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Casual Podcast Host", id: "33045fd9-8010-43f6-b6b0-da3fbf326c29", accent: "American", age: "Young", gender: "Female" },
				{ name: "Charismatic Politician Man", id: "4b305eef-58eb-455c-a154-be40c3129d0b", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Charming Cowgirl", id: "3f636d17-44c7-4872-93d1-0c8f51c916a3", accent: "American", age: "Young", gender: "Female" },
				{ name: "Cheerful Canadian", id: "dd39f331-a857-4c20-908a-1f0c56b0a79b", accent: "Canadian", age: "Young", gender: "Male" },
				{ name: "Cheerful Irishman", id: "d8de3d55-9fcc-4aad-ac93-131141602717", accent: "Irish", age: "Middle-Aged", gender: "Male" },
				{ name: "Classical Film Actor", id: "fcd2297b-44dd-4115-97af-a13297afb8cb", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Classical Film Actress", id: "faf64860-5d8c-44b2-9fc3-88717d307ce8", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Colorful Fashion Influencer", id: "a2cff8f5-1550-4597-9139-63ac4a468b48", accent: "British", age: "Young", gender: "Male" },
				{ name: "Colton Rivers", id: "d8ab67c6-953d-4bd8-9370-8fa53a0f1453", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Comforting Male Conversationalist", id: "99d2cb9c-9011-4ead-8734-641656d3df66", accent: "Black American", age: "Middle-Aged", gender: "Male" },
				{ name: "Comical Vampire", id: "39e3bc67-3cac-477e-910c-0bb91f3191a8", accent: "Eastern European", age: "Middle-Aged", gender: "Male" },
				{ name: "Conversational English Guy", id: "d1248151-8613-41c1-b524-4ce242b02090", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Cool Journalist", id: "f3f69312-095c-4ec3-8e50-6961c676e898", accent: "American", age: "Young", gender: "Female" },
				{ name: "Deep Male Conversational Voice", id: "9c5a3d53-4a8c-4fa2-adad-8e61a830d0e8", accent: "American", age: "Young", gender: "Male" },
				{ name: "Demure Conversationalist", id: "d6fd5cc2-53e6-4e80-ba83-93972682386a", accent: "American", age: "Young", gender: "Female" },
				{ name: "Donovan Sinclair", id: "f042c0be-b7cc-4a59-bea2-65f23e12c710", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Dramatic Movie Trailer Narrator", id: "c11052f5-96df-4c0e-9bba-07e0ad19c4b3", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Dungeon Master", id: "44cb3a51-07b4-4934-83fd-9d9e8d363ce6", accent: "American", age: "Young", gender: "Male" },
				{ name: "Ellie", id: "21289f74-417c-422c-be9f-b8f84ee07d44", accent: "American", age: "Young", gender: "Female" },
				{ name: "English Casual Conversationalist", id: "5add9038-28df-40a6-900c-2f736d008ab3", accent: "British", age: "Middle-Aged", gender: "Female" },
				{ name: "English Children's Book Narrator", id: "a3cc3538-c557-45e0-ada0-b022937d51c1", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Excitable British Naturalist", id: "36e7572e-f5b2-477e-ae61-4400dbeaa034", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Expressive Girl", id: "6b530c02-5a80-4e60-bb68-f2c171c5029f", accent: "American", age: "Young", gender: "Female" },
				{ name: "Fastidious Robo-Butler", id: "661ab31e-c4d6-4a16-952a-b5806a9b4ad1", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Female Meditation Guide", id: "b270ea4b-d169-4d1b-83c4-2e816e947522", accent: "American", age: "Young", gender: "Female" },
				{ name: "French Chef", id: "f8a649d1-0fb6-4168-a1e2-e9ec41937c55", accent: "French", age: "Middle-Aged", gender: "Male" },
				{ name: "Friendly Kiwi Girl", id: "35fc083c-a935-40cb-8cfe-805e76009041", accent: "New Zealand", age: "Young", gender: "Female" },
				{ name: "Friendly Kiwi Guy", id: "1200f557-fdf2-4960-8954-6a0591513051", accent: "New Zealand", age: "Young", gender: "Male" },
				{ name: "Friendly Troll", id: "9c2fa3e6-7bbf-4e71-8838-3d28f26cc269", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Geraldine Wallace", id: "06646694-ba2a-4bca-ae3c-71d79c6b04a3", accent: "American", age: "Old", gender: "Female" },
				{ name: "Ghost With Unfinished Business", id: "2c0e2c10-ac19-4aac-93d0-29c385d7364e", accent: "American", age: "Young", gender: "Male" },
				{ name: "Grizzled New Yorker", id: "9388af0d-4d33-4cdf-8b0a-f003b6cf9455", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Groovy Guy", id: "7e65fb10-8ef6-4faf-a111-875102d51b25", accent: "American", age: "Young", gender: "Male" },
				{ name: "Highly Reactive Guy", id: "da0a369e-7799-40d3-b5c8-3015f198ef57", accent: "American", age: "Young", gender: "Male" },
				{ name: "Imani Carter", id: "96ee3964-5f3f-4a5a-be09-393e833aaf0e", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Indian Actor", id: "710e69a0-ea28-4165-8b2f-c3453686b595", accent: "Indian", age: "Middle-Aged", gender: "Male" },
				{ name: "Indian Actress", id: "1fe215ab-513c-4fc8-9233-fa64b65073ab", accent: "Indian", age: "Middle-Aged", gender: "Female" },
				{ name: "Inspiring Man", id: "8c7d03bd-20d4-40e9-aca1-0469af8ae450", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Inspiring Older Guy", id: "de314c2f-0013-4e7c-92d0-f60ca114ff5b", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Inspiring Woman", id: "b201d214-914c-4d0a-b8e4-54adfc14a0dd", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Ito", id: "f60ecf9e-ff1e-4bae-9206-dba7c653a69e", accent: "American", age: "Young", gender: "Male" },
				{ name: "James the Archivist", id: "81c3cff8-5ac2-4411-be82-81e92fa73838", accent: "British", age: "Young", gender: "Male" },
				{ name: "Kora", id: "59cfc7ab-e945-43de-ad1a-471daa379c67", accent: "American", age: "Young", gender: "Female" },
				{ name: "Lady Elizabeth", id: "c7aa10be-57c1-4647-9306-7ac48dde3536", accent: "British", age: "Old", gender: "Female" },
				{ name: "Literature Professor", id: "5cad536a-3013-4f01-8390-d6d405d266a9", accent: "Eastern European", age: "Middle-Aged", gender: "Male" },
				{ name: "Live Comedian", id: "cb1a4fae-dad5-4729-bd73-a43f570b9117", accent: "American", age: "Young", gender: "Male" },
				{ name: "Male Australian Naturalist", id: "6b69954e-6c9a-4ade-ad03-f73e116e1eae", accent: "Australian", age: "Young", gender: "Male" },
				{ name: "Male English Actor", id: "9e068547-5ba4-4c8e-8e03-69282a008f04", accent: "British", age: "Young", gender: "Male" },
				{ name: "Male Podcaster", id: "01854384-4e4e-48d4-90d1-b22f760a58b5", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Male Protagonist", id: "82a76fb8-3524-4e87-9265-9795c8e4ede6", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Medieval Peasant Man", id: "a1e5674e-3ef1-4394-913c-d4cd70b96801", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Medieval Peasant Woman", id: "a6984261-4b9f-492c-a5fd-9ddbe14039c4", accent: "British", age: "Middle-Aged", gender: "Female" },
				{ name: "Medieval Town Crier", id: "0366be28-522b-432b-b346-119d5f21c3f2", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Mrs. Pembroke", id: "375cd12e-8216-4c6d-8d79-5dfd56fe19f5", accent: "British", age: "Old", gender: "Female" },
				{ name: "Mysterious Woman", id: "f898a92e-685f-43fa-985b-a46920f0650b", accent: "British", age: "Middle-Aged", gender: "Female" },
				{ name: "Nasal Podcast Host", id: "203d3e34-e50b-48ab-a782-835fa39c36c6", accent: "American", age: "Young", gender: "Male" },
				{ name: "Nature Documentary Narrator", id: "176a55b1-4468-4736-8878-db82729667c1", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "New York Comedian Guy", id: "28441f64-64a0-4df4-9bd2-478850ee5fac", accent: "American", age: "Young", gender: "Male" },
				{ name: "Old School Radio Announcer", id: "88e0c3f6-6f99-4e37-a3f4-a053869d6bd4", accent: "American", age: "Old", gender: "Male" },
				{ name: "Old-Timey English Priest", id: "27019e54-59c4-4400-a51c-7e5fd2142029", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Opinionated Guy", id: "89989d92-1de8-4e5d-97e4-23cd363e9788", accent: "American", age: "Young", gender: "Male" },
				{ name: "Pirate Captain", id: "2bc0fca6-d591-4855-abef-ec048a385e8f", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Rajesh", id: "8b9ed861-3382-455d-9c03-a40671943d6b", accent: "Indian", age: "Young", gender: "Male" },
				{ name: "Relaxing ASMR Woman", id: "aeaaf1f8-fe31-49ae-893d-c744e5207bc2", accent: "American", age: "Young", gender: "Female" },
				{ name: "Sad Old British Man", id: "55813df9-fdbb-4ec2-a539-1b91fd750ca6", accent: "British", age: "Old", gender: "Male" },
				{ name: "Scottish Guy", id: "a48360cb-14f3-460c-93f2-b38deb45400b", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Scottish Scott", id: "f49f18fc-4fe9-4e78-9338-0960d44b93f9", accent: "Scottish", age: "Middle-Aged", gender: "Male" },
				{ name: "Seasoned Midwestern Actress", id: "27e8dd8b-7e7c-4c1f-bfb2-c1b016487343", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Sebastian Lockwood", id: "522fc367-961f-4817-8929-81f433b4afe9", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Serene Assistant", id: "71de875d-bc14-4ed5-87da-8584ba4ea247", accent: "American", age: "Young", gender: "Female" },
				{ name: "Sir Spandrel", id: "921ece15-27c1-4028-b6ac-82d2d93f65c4", accent: "British", age: "Middle-Aged", gender: "Male" },
				{ name: "Sitcom Girl", id: "5bbc32c1-a1f6-44e8-bedb-9870f23619e2", accent: "American", age: "Young", gender: "Female" },
				{ name: "Sitcom Guy", id: "c5be03fa-09cc-4fc3-8852-7f5a32b5606c", accent: "American", age: "Young", gender: "Male" },
				{ name: "Soft Male Conversationalist", id: "b152864b-6720-496a-9d18-eaadb31516ee", accent: "American", age: "Young", gender: "Male" },
				{ name: "Steve Frisch", id: "f4703974-b6a1-45c8-ac72-72ea06e3dd43", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Terrence Bentley", id: "7f633ac4-8181-4e0d-99e1-11a4ef033691", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "TikTok Fashion Influencer", id: "ebba4902-69de-4e01-9846-d8feba5a1a3f", accent: "American", age: "Young", gender: "Female" },
				{ name: "Tough Guy", id: "6a42908a-f332-4c39-a93a-98c7d6017f12", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Trevor", id: "41745808-6790-4be4-83db-363e20db7e71", accent: "American", age: "Young", gender: "Male" },
				{ name: "Turtle Guru", id: "e722344d-e09a-489d-9f10-b67a28edd35a", accent: "American", age: "Old", gender: "Male" },
				{ name: "Unserious Movie Trailer Narrator", id: "2ca55181-9d21-43b3-9e6e-0cb24a669e6c", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Unserious TV Host", id: "a5b1def0-16a5-4fcc-bfa8-2a0de2e35d93", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Vince Douglas", id: "ee96fb5f-ec1a-4f41-a9ba-6d119e64c8fd", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Warm American Female", id: "8a7dd58c-0cda-4073-9ce6-654184695e99", accent: "American", age: "Young", gender: "Female" },
				{ name: "Warm Female Assistant Voice", id: "a623d3ed-612c-413b-b09f-e0a379a317f0", accent: "American", age: "Middle-Aged", gender: "Female" },
				{ name: "Warm Welsh Lady", id: "f33a4a30-d1bc-450e-9174-082dec6aa571", accent: "Welsh", age: "Middle-Aged", gender: "Female" },
				{ name: "Welsh Folk Storyteller", id: "4a9c32ab-e7b5-4439-a7be-54cca5ad9c07", accent: "Welsh", age: "Middle-Aged", gender: "Male" },
				{ name: "Wise Wizard", id: "e7024495-03e7-4e8b-8b22-27c54ee25ffa", accent: "British", age: "Old", gender: "Male" },
				{ name: "Wrestling Announcer", id: "dc6f3593-4ae1-46eb-9121-b872ad7ba1a0", accent: "American", age: "Middle-Aged", gender: "Male" },
				{ name: "Yorkshire Chap", id: "2ae087da-ab61-4455-b095-4e926f0e75a2", accent: "British", age: "Middle-Aged", gender: "Male" }
			],
			defaultVoiceID: "f60ecf9e-ff1e-4bae-9206-dba7c653a69e",
			providers: [
				{	name:"Anthropic", id:"ANTHROPIC",
					models: [
						{ name:"Claude Sonnet 4.5", id:"claude-sonnet-4-5-20250929" },
						{ name:"Claude Haiku 4.5", id:"claude-haiku-4-5-20251001" },
						{ name:"Claude Sonnet 4", id:"claude-sonnet-4-20250514" },			
						{ name:"Claude Sonnet 3.7", id:"claude-3-7-sonnet-latest" },
					],
				},
				{	name:"Google", id:"GOOGLE",
					models: [
						{ name:"Gemini 2.5 Flash", id:"gemini-2.5-flash" },
					],
				},
				{	name:"OpenAI", id:"OPEN_AI",
					models: [
						{ name:"GPT 5", id:"gpt-5" },
						{ name:"GPT 5 Mini", id:"gpt-5-mini" },
						{ name:"GPT 5 Nano", id:"gpt-5-nano" },
						{ name:"GPT 4.1", id:"gpt-4.1" },
						{ name:"GPT 4o", id:"gpt-4o" },
					],
				},
			],
			defaultProviderID: "ANTHROPIC",
			defaultModelID: "claude-haiku-4-5-20251001",
		},
		openai: {
			color: "#00afba",
			icon:  { texture:{ path: "openai-logo.png" }, width:64, height:64 },
			iconSmall: { texture:{ path: "openai-logo-small.png" }, width:24, height:24 },
			key: config.openAIKey,
			title: "OpenAI Realtime",
			specifier: "openAIRealtime",
			transcript: true,
			voices: [
				{ name:"Alloy", id:"alloy" },
				{ name:"Ash", id:"ash" },
				{ name:"Ballad", id:"ballad" },
				{ name:"Cedar", id:"cedar" },
				{ name:"Coral", id:"coral" },
				{ name:"Echo", id:"echo" },
				{ name:"Marin", id:"marin" },
				{ name:"Sage", id:"sage" },
				{ name:"Shimmer", id:"shimmer" },
				{ name:"Verse", id:"verse" },
			],
			defaultVoiceID: "marin",
			defaultProviderID: "",
			defaultModelID: "",
		}
	}
};

export default Object.freeze(assets, true);
