/*
 * Copyright (c) 2022-2026  Moddable Tech, Inc.
 *
 *   This file is part of the Moddable SDK Tools.
 * 
 *   The Moddable SDK Tools is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 * 
 *   The Moddable SDK Tools is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 * 
 *   You should have received a copy of the GNU General Public License
 *   along with the Moddable SDK Tools.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
	Portions, particularly xsdbRouter, generated by Claude Code and Google Antigravity. Beware.
*/

let net, exec, spawn, fs, LogMachine, Machine;

try {
	net = require('node:net');
	const cp = require('node:child_process');
	exec = cp.exec;
	spawn = cp.spawn;
	fs = require('node:fs');
	Machine = require('./xsbug-machine.js').Machine;
	if (process.env.XSBUG_LOGMACHINE)
		LogMachine = require(process.env.XSBUG_LOGMACHINE).LogMachine;
	else
		LogMachine = require('./xsbug-debugmachine.js').LogMachine;
}
catch (e) {
	if ("MODULE_NOT_FOUND" === e.code) {
		console.log("#xsbug-log missing modules! Did you npm install?");
		console.log("   pushd $MODDABLE/tools/xsbug-log && npm install && popd");
	}
	else
		console.log("#xsbug-log start-up error: " + e);
	process.exit();
}

const portIn = process.env.XSBUG_LOG_PORT ?? 5002;
let connections = 0;
let autoexit = false;

let probe = net.connect({
	port: portIn,
	host: "127.0.0.1"
});
probe.setEncoding("utf8");
probe.on('ready', data => {
	probe.destroy();
	const readline = require('node:readline');
	const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
	rl.question(`xsdb: Port ${portIn} is already in use (app or instance running).\nForcefully terminate the app holding the port? (y / n) `, (answer) => {
		rl.close();
		if (answer.trim().toLowerCase().startsWith('y')) {
			const isWin = process.platform === 'win32';
			const cmd = isWin 
				? `FOR /F "tokens=5" %P IN ('netstat -ano ^| findstr :${portIn}') DO taskkill /PID %P /F`
				: `kill -9 $(lsof -t -i :${portIn})`;

			exec(cmd, (err, stdout, stderr) => {
				setTimeout(launch, 500);
			});
		} else {
			console.log('Exiting.');
			process.exit(-1);
		}
	});
});
probe.on('error', error => {
	// no debugger detected. continue.
	probe.destroy();
	launch();
});

const xsdbRouter = {
	machines: [],
	activeThreadId: 0,
	nextThreadId: 1,
	showMcsim: false,

	prefsPath() {
		try { return require('node:path').join(process.env.XSBUG_PROJECT || process.cwd(), '.xsdb.json'); } catch (e) { return null; }
	},
	loadPrefs() {
		try {
			const p = this.prefsPath();
			if (p && fs.existsSync(p)) {
				const data = JSON.parse(fs.readFileSync(p, 'utf8'));
				if (data.showMcsim !== undefined) this.showMcsim = data.showMcsim;
				if (data.outputFormat !== undefined) this.globalOutputFormat = data.outputFormat;
				if (data.exceptionsMode !== undefined) this.globalExceptionsMode = data.exceptionsMode;
				if (data.breakOnStart !== undefined) this.globalBreakOnStart = data.breakOnStart;
				if (Array.isArray(data.breakpoints)) this.globalBreakpoints = data.breakpoints;
				if (data.breakpointIdCounter !== undefined) this.globalBreakpointIdCounter = data.breakpointIdCounter;
			}
		} catch (e) {}
		this.globalBreakOnStart = this.globalBreakOnStart ?? false;
		this.globalExceptionsMode = this.globalExceptionsMode ?? 'off';
		this.globalOutputFormat = this.globalOutputFormat ?? 'text';
		this.globalBreakpoints = this.globalBreakpoints ?? [];
		if (this.globalBreakpointIdCounter === undefined) {
			this.globalBreakpointIdCounter = 0;
			this.globalBreakpoints.forEach(bp => {
				if (bp.id === undefined) bp.id = ++this.globalBreakpointIdCounter;
				else this.globalBreakpointIdCounter = Math.max(this.globalBreakpointIdCounter, bp.id);
			});
		}
	},
	savePrefs() {
		try {
			const p = this.prefsPath();
			if (p) {
				if (this.globalBreakpoints && this.globalBreakpoints.length === 0)
					this.globalBreakpointIdCounter = 0;

				fs.writeFileSync(p, JSON.stringify({
					showMcsim: this.showMcsim,
					outputFormat: this.globalOutputFormat,
					exceptionsMode: this.globalExceptionsMode,
					breakOnStart: this.globalBreakOnStart,
					breakpoints: this.globalBreakpoints,
					breakpointIdCounter: this.globalBreakpointIdCounter
				}));
			}
		} catch (e) {}
	},

	isHidden(m) {
		return m && !m.interactive && !this.showMcsim;
	},

	getMachine(id) {
		return this.machines.find(m => m && m.id === id) || null;
	},

	init() {
		this.loadPrefs();
		this.rl = require('node:readline').createInterface({
			input: process.stdin,
			output: process.stdout,
			prompt: '(xsdb) ',
			completer: (line, callback) => {
				const m = this.getMachine(this.activeThreadId);
				if (m && typeof m.completer === 'function')
					m.completer(line, callback);
				else
					callback(null, [[], line]);
			}
		});

		// Suppress TAB processing while completions are displayed
		const origTabComplete = this.rl._tabComplete;
		this.rl._tabComplete = function(lastKeypressWasTab) {
			const m = this.completer && this._router?.getMachine(this._router.activeThreadId);
			if (m && m.completionsShown)
				return;
			origTabComplete.call(this, lastKeypressWasTab);
		};
		this.rl._router = this;

		this.rl.on('line', (line) => {
			const active = this.getMachine(this.activeThreadId);
			if (active) active.promptShown = false;

			const str = line.trim();
			if (str === 'set mcsim on' || str === 'set mcsim off') {
				this.showMcsim = str === 'set mcsim on';
				this.savePrefs();
				if (active) {
					active.report('set', { showMcsim: this.showMcsim }, undefined, () => {
						console.log(`mcsim thread: ${this.showMcsim ? 'on' : 'off'}`);
						active.showPrompt();
					});
				} else {
					console.log(`mcsim thread: ${this.showMcsim ? 'on' : 'off'}`);
				}
				return;
			}
			if (str.startsWith('info threads')) {
				const threadsData = this.machines.map(m => {
					if (!m) return null;
					if (m.id === undefined) return null;
					if (this.isHidden(m)) return null;
					return {
						id: m.id,
						active: m.id === this.activeThreadId,
						name: m.title || `worker-${m.id}`,
						state: !m.connected ? 'Disconnected' : (m.running ? 'Running' : 'Stopped'),
						path: (!m.connected || m.running) ? undefined : (m.currentPath || 'unknown'),
						line: (!m.connected || m.running) ? undefined : (m.currentLine || '?')
					};
				}).filter(Boolean);

				if (active) {
					active.currentCommand = 'info_threads';
					active.report('info_threads', { threads: threadsData }, undefined, (data) => {
						console.log('  Id   Name               State');
						data.threads.forEach(t => {
							const sel = t.active ? '*' : ' ';
							const stateStr = t.state === 'Stopped' ? `Stopped at ${t.path}:${t.line}` : t.state;
							console.log(`${sel} ${t.id.toString().padEnd(4)} ${t.name.padEnd(18)} ${stateStr}`);
						});
					});
					active.showPrompt();
				} else {
					console.log('  Id   Name               State');
					threadsData.forEach(t => {
						const sel = t.active ? '*' : ' ';
						const stateStr = t.state === 'Stopped' ? `Stopped at ${t.path}:${t.line}` : t.state;
						console.log(`${sel} ${t.id.toString().padEnd(4)} ${t.name.padEnd(18)} ${stateStr}`);
					});
				}
				return;
			}
			const isThreadApply = str === 'thread apply' || str.startsWith('thread apply ') || str === 't apply' || str.startsWith('t apply ');
			if (isThreadApply) {
				const prefixLen = str.startsWith('t apply') ? 7 : 12;
				const args = str.substring(prefixLen).trim();
				if (args.startsWith('all ')) {
					const cmd = args.substring(4).trim();
					this.machines.forEach(m => {
						if (!m) return;
						if (m.id === undefined) return;
						if (this.isHidden(m)) return;
						const name = m.title || `worker-${m.id}`;
						console.log(`Thread ${m.id} (${name}):`);
						m.handleCommand(cmd);
					});
				} else {
					const match = args.match(/^([\d\s]+)\s+(.+)$/);
					if (match) {
						const ids = match[1].split(/\s+/).map(x => parseInt(x));
						const cmd = match[2];
						ids.forEach(id => {
							const m = this.getMachine(id);
							if (m) {
								const name = m.title || `worker-${id}`;
								console.log(`Thread ${id} (${name}):`);
								m.handleCommand(cmd);
							} else if (active) {
								active.currentCommand = 'thread';
								active.commandError(`Thread ID ${id} not known.`);
							}
						});
					} else if (active) {
						active.currentCommand = 'thread';
						active.commandError('Usage: thread apply [all | <id1> <id2>...] <command>');
					}
				}
				if (active) active.showPrompt();
				return;
			}
			if (str === 'thread' || str === 't' || str.startsWith('thread ') || str.startsWith('t ')) {
				const match = str.match(/^(?:thread|t)\s+(\d+)$/);
				if (match) {
					const id = parseInt(match[1]);
					const m = this.getMachine(id);
					if (m && this.isHidden(m)) {
						if (active) {
							active.currentCommand = 'thread';
							active.commandError(`Thread ${id} is hidden (mcsim). Use "set mcsim on" to show.`);
							active.showPrompt();
						}
					} else if (m) {
						this.activeThreadId = id;
						m._clearLineGlobal();
						const name = m.title || `worker-${id}`;
						m.currentCommand = 'thread';
						m.report('thread', { id, name }, undefined, (data) => {
							console.log(`[Switching to thread ${data.id} (${data.name})]`);
						});
						if (!m.running) m.printLocation();
						m.showPrompt();
					} else {
						if (active) {
							active.currentCommand = 'thread';
							active.commandError(`Thread ID ${id} not known.`);
						}
					}
				} else {
					if (active) {
						active.currentCommand = 'thread';
						active.commandError('Usage: thread <id>');
					}
				}
				return;
			}

			if (str === 'quit' || str === 'q') {
				if (active)
					active.handleCommand(str);
				else
					process.exit(0);
				return;
			}

			if (active)
				active.handleCommand(str);
			else {
				console.log('No active connection. Waiting for device...');
				this.rl.prompt(true);
			}
		});

		this.rl.on('close', () => {
			if (!process.stdin.isTTY) return;
			this.machines.forEach(m => {
				if (m && m.connected) m.doAbort();
			});
			process.exit(0);
		});

		this.rl.on('SIGINT', () => {
			const active = this.getMachine(this.activeThreadId);
			if (active) {
				if (active.running) active.doStep();
				else {
					console.log('');
					console.log('Use "quit" to exit.');
					active.promptShown = false;
					active.showPrompt();
				}
			}
			else {
				console.log('');
				console.log('No active connection. Use "quit" to exit.');
				this.rl.prompt(true);
			}
		});
	},

	addMachine(target) {
		if (!this.rl) this.init();

		const m = new LogMachine(target, target);

		// Map router extensions cleanly into the Machine so it interfaces with the global rl natively.
		m.rl = this.rl;
		m._clearLineGlobal = () => {
			if (m.promptShown) {
				this.rl.output.write('\x1B[2K\x1B[0G');
				m.promptShown = false;
			}
		};
		// Override Machine's clearLine natively
		m.clearLine = m._clearLineGlobal;

		if (!this.globalBreakpoints) this.globalBreakpoints = [];
		m.breakpoints = this.globalBreakpoints;
		m.getNextBreakpointId = () => {
			return ++this.globalBreakpointIdCounter;
		};

		// Broadcast breakpoint changes to all connected machines.
		const baseDoSetBreakpoint = Machine.prototype.doSetBreakpoint;
		const baseDoClearBreakpoint = Machine.prototype.doClearBreakpoint;
		const baseDoClearAllBreakpoints = Machine.prototype.doClearAllBreakpoints;

		m.doSetBreakpoint = (path, line, options) => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoSetBreakpoint.call(mach, path, line, options);
			});
		};

		m.doClearBreakpoint = (path, line) => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoClearBreakpoint.call(mach, path, line);
			});
		};

		m.doClearAllBreakpoints = () => {
			this.machines.forEach(mach => {
				if (mach && mach.connected)
					baseDoClearAllBreakpoints.call(mach);
			});
		};

		m.outputFormat = this.globalOutputFormat;
		m.exceptionsMode = this.globalExceptionsMode;
		m.breakOnStart = this.globalBreakOnStart;
		const originalCmdSet = m.cmdSet.bind(m);
		m.cmdSet = (args) => {
			originalCmdSet(args);
			let save = false;
			if (args[0] === 'output') { this.globalOutputFormat = m.outputFormat; save = true; }
			if (args[0] === 'exceptions') { this.globalExceptionsMode = m.exceptionsMode; save = true; }
			if (args[0] === 'start') { this.globalBreakOnStart = m.breakOnStart; save = true; }
			if (save) {
				this.machines.forEach(mach => {
					if (mach && mach !== m) {
						mach.outputFormat = this.globalOutputFormat;
						mach.exceptionsMode = this.globalExceptionsMode;
						mach.breakOnStart = this.globalBreakOnStart;
					}
				});
				this.savePrefs();
			}
		};

		const originalCmdBreak = m.cmdBreak.bind(m);
		m.cmdBreak = (args) => {
			originalCmdBreak(args);
			this.savePrefs();
		};

		const originalCmdClear = m.cmdClear.bind(m);
		m.cmdClear = (args) => {
			originalCmdClear(args);
			this.savePrefs();
		};

		const originalCmdDelete = m.cmdDelete.bind(m);
		m.cmdDelete = (args) => {
			originalCmdDelete(args);
			this.savePrefs();
		};

		const originalCmdCondition = m.cmdCondition.bind(m);
		m.cmdCondition = (args) => {
			originalCmdCondition(args);
			this.savePrefs();
		};

		const originalCmdTrace = m.cmdTrace.bind(m);
		m.cmdTrace = (args) => {
			originalCmdTrace(args);
			this.savePrefs();
		};

		const originalCmdHitcount = m.cmdHitcount.bind(m);
		m.cmdHitcount = (args) => {
			originalCmdHitcount(args);
			this.savePrefs();
		};

		this.machines.push(m);
		m.onBreakpointHit = () => {
			if (this.isHidden(m)) return;
			if (this.activeThreadId !== m.id) {
				if (m.outputFormat !== 'json') {
					m._clearLineGlobal();
					const name = m.title || `worker-${m.id}`;
					console.log(`\n[Switching to thread ${m.id} (${name})]`);
				}
				this.activeThreadId = m.id;
			}
		};
		m.onTitleReady = () => {
			if (m.interactive) {
				m.id = this.nextThreadId++;
			} else {
				m.id = 0;
			}
			const activeMach = this.getMachine(this.activeThreadId);
			if (!this.isHidden(m) && (!activeMach || this.isHidden(activeMach)))
				this.activeThreadId = m.id;
		};
		return m;
	}
};

function launch() {
	const server = net.createServer(target => {
		connections++;
		target.setEncoding("utf8");
		target.on('error', (e) => {
			if (target.machine?.title)
				console.log(`#xsbug-log socket error for "${target.machine.title}": ${e.message}`);
		});
		target.on('close', () => {
			if (target.machine) {
				if (target.machine.title && ("mcsim" !== target.machine.title))
					target.machine.print(`#xsbug-log disconnected from "${target.machine.title}"`);

				const isDyingActive = (xsdbRouter.activeThreadId === target.machine.id);

				const idx = xsdbRouter.machines.indexOf(target.machine);
				if (idx !== -1) xsdbRouter.machines[idx] = null;
				target.machine = null;

				if (isDyingActive) {
					xsdbRouter.activeThreadId = 0;
					const fallback = xsdbRouter.machines.find(m => m && !xsdbRouter.isHidden(m));
					if (fallback)
						xsdbRouter.activeThreadId = fallback.id;
					else if (xsdbRouter.rl)
						xsdbRouter.rl.prompt(true);
				}

				if (!xsdbRouter.machines.some(m => m))
					xsdbRouter.nextThreadId = 1;
			}

			if ((0 === --connections) && autoexit)
				process.exit(0);
		});

		target.machine = xsdbRouter.addMachine(target);
	});

	server.listen(portIn, () => {
	   console.log(`xsdb listening on port ${portIn}. Type "quit" to exit.`);
	});

	let args = process.argv.slice(2);
	if (args.length === 0) {
		console.log("xsdb: no command line arguments. Waiting for connection.");
		return;
	}

	// Intercept OS-detaching execution hooks
	if (args.length >= 2 && args[0] === 'open' && (args[1] === '-a' || args[1] === '-W')) {
		args = args.slice(2);
		// Remap macOS .app bundles to their internal WindowServer binary
		if (args[0] && args[0].endsWith('.app')) {
			const appName = args[0].split('/').pop().replace('.app', '');
			let binaryPath = `${args[0]}/Contents/MacOS/${appName}`;
			if (!fs.existsSync(binaryPath)) {
				binaryPath = `${args[0]}/Contents/MacOS/main`;
			}
			if (fs.existsSync(binaryPath)) {
				args[0] = binaryPath;
			}
		}
	} else if (args.length >= 2 && args[0] === 'start' && args[1] === '/B') {
		args = args.slice(2);
	}

	// In the extremely rare event all arguments were stripped, abort.
	if (args.length === 0) return;

	try {
		const targetBin = args[0];
		const targetArgs = args.slice(1);

		// Spawn exactly the explicit child process while deliberately stripping its
		// stdin authority to cleanly preserve native readline logic underneath xsdb.
		// We also 'ignore' stdout so raw C logs don't double-print over xsdb's natively parsed TCP XML log traces.
		const child = spawn(targetBin, targetArgs, { stdio: ['ignore', 'ignore', 'inherit'] });

		child.on('error', (err) => {
			console.log(`\n#xsbug-log child process error: ${err.message}`);
		});

		child.on('exit', (code) => {
			if (connections === 0 && autoexit) {
				console.log(`\n#xsbug-log simulator cleanly executed or terminated before connecting. Exiting.`);
				process.exit(code || 0);
			}
		});

		// Map structural tear down if the LLM kills xsdb natively
		process.on('SIGINT', () => {
			child.kill('SIGTERM');
			process.exit();
		});
		process.on('exit', () => {
			child.kill('SIGTERM');
		});
	} catch (e) {
		console.log(`#xsbug-log explicit spawn exception: ${e.message}`);
	}
}
