// Generated by write_buildconfig_header.py
// From "//third_party/connectedhomeip/src/ble:gen_ble_buildconfig"

#ifndef BLE_BLEBUILDCONFIG_H_
#define BLE_BLEBUILDCONFIG_H_

#define CONFIG_NETWORK_LAYER_BLE 1
#define CHIP_ENABLE_CHIPOBLE_TEST 0
#define BLE_PLATFORM_CONFIG_INCLUDE "platform/ESP32/BlePlatformConfig.h"

#endif  // BLE_BLEBUILDCONFIG_H_
